### ISSUE TITLE
Roadmap for jplyr 0.0.1

### ISSUE THREAD

**Issue by davidagold** [davidagold/_AbstractTables.jl#3]
I don't know if it's appropriate to register this package, since its purpose is solely to demonstrate how one might extend the jplyr querying interface in a manner generic over in-memory Julia tabular data structures. However, I will want people to be able to play around with this interface.

[EDIT 9/20/16]: I've renamed the package to _AbstractTables.jl in order to emphasize that this package is an experiment and a demonstration. I intend to register it under this name.

In any case, here's what needs to happen before 0.0.1:
- [x] `show` machinery needs to be improved #1 
- [ ] Documentation for querying functionality
- [x] Figure out return type of `summarize` over `Grouped{T}` #4
- [ ] Tag v0.0.1 and register this package

Goals for jplyr v0.0.2 and beyond:
- [ ] Lifting regime needs to be revised #2 

[EDIT 9/20/16]: I don't want to delay tagging v0.0.1 of jplyr.jl on account of waiting for lifting machinery updates. The current lifting regimen works fine, but doesn't allow for the sort of custom lifting required to implement 3VL. That's acceptable to me for a jplyr 0.0.1 release.
